### ISSUE TITLE
MVC page

### ISSUE THREAD

**Issue by fasteddys** [neozhu/visitormanagement#2]
Hello, this is a very nice solution, can we get swagger and MVC pages,

**Comment by neozhu** [comment]
yes, You can modify it according to your own needs;
In addition, I recommend you to look at this project https://github.com/fullstackhero/dotnet-webapi-boilerplate

**Comment by fasteddys** [comment]
I saw that, its great but it does not have MVC view, it pointed me to look here https://github.com/fullstackhero/dotnet-mvc-boilerplate but its empty
