### ISSUE TITLE
Web APIs 

### ISSUE THREAD

**Issue by AbuHelweh** [neozhu/visitormanagement#4]
Greetings

Im interested to know if you are using web APIs in your project?
Dose the architecture consider multi-tenant (multi-customer)?

**Comment by neozhu** [comment]
Sorry, I have no plans to implement web api back-end service, you can take look at this project https://github.com/blazorhero/CleanArchitecture
I have implemented multi-tenancy for this project, you can refer to
https://github.com/neozhu/CleanArchitectureWithBlazorServer
