### ISSUE TITLE
ExceptionHandlingMiddleware seems to not catch a global exception

### ISSUE THREAD

**Issue by alexvazquez** [neozhu/visitormanagement#5]
Congratulations for the great architecture.

I tried to see if `ExceptionHandlingMiddleware `was working, so I placed a breakpoint after login here:

![image](https://user-images.githubusercontent.com/347747/190019150-29542a09-c668-4017-aa03-7b58ffc5e56f.png)

And then I set the `request` object to be null to generate an exception as in the following image.

![image](https://user-images.githubusercontent.com/347747/190019552-27e61e85-bd91-49c4-99d5-3b1fa8bfba98.png)

I had a breakpoint in the `ExceptionHandingMiddleware `class here:

![image](https://user-images.githubusercontent.com/347747/190019229-70357658-a697-46a5-ad6a-228c541b64c6.png)

To see if the line was hit but it never gets into that catch statement.

Any clue?

**Comment by neozhu** [comment]
ExceptionHandlingMiddleware  just catches MediaR handle.

**Comment by alexvazquez** [comment]
> ExceptionHandlingMiddleware just catches MediaR handle.

Is there a way to have a global exception handler for everything?

I was reading there is Error Boundaries in .NET6, is that implemented in this project for handing exceptions? Appreciate it

**Comment by neozhu** [comment]
Error Boundaries is working for the page level. as I know
